apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output-generator
          image: log-output-app-generator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          # volumeMounts:
          #   - name: shared-storage
          #     mountPath: /app/shared
          env:
            - name: PING_PONG_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # - name: SHARED_VOLUME_PATH
            #   value: "/app/shared/request_count.txt"
        - name: log-output-status
          image: log-output-app-status:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8002
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
          # volumeMounts:
          #   - name: shared-storage
          #     mountPath: /app/shared
          #     readOnly: true
          env:
            - name: PING_PONG_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # - name: SHARED_VOLUME_PATH
            #   value: "/app/shared/request_count.txt"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
      volumes:
        - name: config-volume
          configMap:
            name: log-output-config
            items:
              - key: information.txt
                path: information.txt
      # volumes:
      #   - name: shared-storage
      #     persistentVolumeClaim:
      #       claimName: shared-storage-claim
      restartPolicy: Always
