apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output-generator
          image: log-output-app-generator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          volumeMounts:
            - name: shared-volume
              mountPath: /app/shared
        - name: log-output-status
          image: log-output-app-status:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8002
              protocol: TCP
          volumeMounts:
            - name: shared-volume
              mountPath: /app/shared
              readOnly: true
      volumes:
        - name: shared-volume
          emptyDir: {}
      restartPolicy: Always
