apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-storage-claim
  labels:
    app: shared-storage
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: shared-storage