apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-deployment
  namespace: default
  labels:
    app: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong-container
        image: ping-pong:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        env:
        - name: PORT
          value: "8002"
      restartPolicy: Always
