apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  labels:
    app: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project-main
          image: project-app-main:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
          volumeMounts:
            - name: cache-volume
              mountPath: /app/shared
        - name: project-backend
          image: project-app-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              value: "8003"
          volumeMounts:
            - name: cache-volume
              mountPath: /app/shared
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: shared-storage-claim
      restartPolicy: Always
