apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-storage-claim
  namespace: project-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Mi
