apiVersion: v1
kind: Service
metadata:
  name: project-svc
spec:
  type: ClusterIP
  selector:
    app: project
  ports:
    - name: http
      protocol: TCP
      port: 1234
      targetPort: 8001
    - name: http-backend
      protocol: TCP
      port: 1235
      targetPort: 8003