apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
spec:
  type: NodePort
  selector:
    app: log-output # This should match the app label in the deployment
  ports:
    - name: http
      nodePort: 30080 # NodePort must be unique in the cluster
      protocol: TCP
      port: 1234
      targetPort: 8000
